### ISSUE TITLE
Progress.Pie renders empty on 4.0.0

### ISSUE THREAD

**Issue by felippepuhle** [oblador/react-native-progress#173]
Just updated to `4.0.0` and suddenly my Progress.Pie isn't rendering anything.

![Screen Shot 2019-10-21 at 9 45 29 AM](https://user-images.githubusercontent.com/15961929/67206242-a4d61800-f3e7-11e9-9a85-da8f0e8c5d91.png)

Tried to apply some background-color and apparently the wrapper is rendering, as I got a yellow square:

![Screen Shot 2019-10-21 at 9 46 13 AM](https://user-images.githubusercontent.com/15961929/67206241-a4d61800-f3e7-11e9-81d4-0fa23f33f16e.png)

This is the expected behavior (v3.6.0)

![Screen Shot 2019-10-21 at 9 52 01 AM](https://user-images.githubusercontent.com/15961929/67206661-7c025280-f3e8-11e9-9ba9-3f7349c295d7.png)

Any thoughts? 

Thanks!

**Comment by oblador** [comment]
The new version uses the community maintained ART library, did you install and configure it?

**Comment by felippepuhle** [comment]
Hey @oblador, thanks for your quick response.

Yes, https://github.com/react-native-community/art is correctly installed and configured (I had to remove [this hack](https://github.com/oblador/react-native-progress/issues/161#issuecomment-530274309) 'cause I was getting "Duplicate symbols" error, so I guess it's ok)

Thanks!

**Comment by alexxgent** [comment]
Same issue with the Circle component for me. Haven't found a workaround yet (other than downgrading).

**Comment by hubertjaruzal** [comment]
@alexxgent Yes, Progress.Circle isn't working on 4.0.0.

**Comment by DrummerSi** [comment]
It seems that " visible={true} " needs adding to the Surface, Circle & Shape components within "Pie.js" for it to work... Unfortunately I'm still unable to get Progress.Circle & Progress.CircleSnail working

**Comment by oblador** [comment]
It seems to be related to this issue in RNC ART: https://github.com/react-native-community/art/issues/30

There's a PR to fix it: https://github.com/react-native-community/art/pull/31

**Comment by felippepuhle** [comment]
Thanks for the heads up @oblador 

Should we close this?

**Comment by oblador** [comment]
Let’s leave it open for me to track that our minimum version should be updated once fixed and for visibility for new users.

Fix for now would be to `yarn add react-native-progress@3`

**Comment by juliafriberg** [comment]
The fix for this has been merged and released https://github.com/react-native-community/art/releases/tag/v1.0.3.

**Comment by oblador** [comment]
Just released [4.0.2](https://github.com/oblador/react-native-progress/releases/tag/v4.0.2) with a bump of RNC ART.

**Comment by felippepuhle** [comment]
It's working, thank you guys!

**Comment by wKovacs64** [comment]
Hmm, the new version throws the following error for me (fresh Expo project on Android):

```
Error while updating property 'stroke' in shadow node of type: ARTShape

Value for stroke cannot be cast from String to ReadableArray
```

I can open a new issue if you'd like, although I'm not sure if it belongs here or in ART.

**Comment by oblador** [comment]
I'd open a new ticket in ART
